apiVersion: v1
kind: Service
metadata:
  name: simple-swan-go-application
spec:
  selector:
    app: simple-swan-go-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
  