name: Developer Onboarding

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'docs/**'

jobs:
  first-contribution-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check if first contribution
        uses: actions/github-script@v6
        with:
          script: |
            const { data: commits } = await github.rest.repos.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              author: context.actor,
              per_page: 1
            });
            
            if (commits.length === 1) {
              console.log(`🎉 Welcome ${context.actor}! This appears to be your first contribution.`);
              console.log('📚 Please read our CONTRIBUTING.md for guidelines.');
              console.log('💡 Remember to create PRs for code review before merging.');
            }

  branch-guidance:
    runs-on: ubuntu-latest
    steps:
      - name: Provide Branch Guidance
        run: |
          echo "✅ Great job working on a feature branch!"
          echo "🌿 Current branch: ${{ github.ref_name }}"
          echo "📋 Workflow reminder:"
          echo "  1. Make your changes on this branch"
          echo "  2. Push commits: git push origin ${{ github.ref_name }}"
          echo "  3. Create PR when ready"
          echo "  4. Wait for review and approval"
          echo "  5. Merge via GitHub UI"